# Generated by Django 3.2.12 on 2022-02-21 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='제목')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='계약 확인 여부')),
                ('is_legal_team_confirmed', models.BooleanField(default=False, verbose_name='법무팀 확인 여부')),
                ('is_finance_team_confirmed', models.BooleanField(default=False, verbose_name='재무팀 확인 여부')),
                ('is_security_team_confirmed', models.BooleanField(default=False, verbose_name='보안팀 확인 여부')),
                ('finance_team_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='재무팀 담당자')),
                ('legal_team_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='법무팀 담당자')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='계약 담당자')),
                ('security_team_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='보안팀 담당자')),
            ],
            options={
                'verbose_name': '계약',
                'verbose_name_plural': '계약 목록',
                'db_table': 'contract',
            },
        ),
    ]
