# Generated by Django 3.2.12 on 2024-05-01 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='제목')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='계약 확인 여부')),
                ('is_private', models.BooleanField(default=False, verbose_name='민감 계약 정보 여뷰')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='계약 담당자')),
            ],
            options={
                'verbose_name': '계약',
                'verbose_name_plural': '계약 목록',
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='ContractReviewDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('NORMAL', 'NORMAL_TEAM'), ('FINANCE', 'FINANCE_TEAM'), ('LEGAL', 'LEGAL_TEAM'), ('SECURITY', 'SECURITY_TEAM'), ('SECURITY_TECH', 'SECURITY_TECH_TEAM'), ('ETC', 'ETC_TEAM')], max_length=15)),
                ('is_confirm', models.BooleanField(default=False, verbose_name='담당자 확인 여부')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='contract.contract', verbose_name='계약')),
                ('manager', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managing_contracts', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
            ],
            options={
                'verbose_name': '계약 승인',
                'verbose_name_plural': '계약 승인 목록',
                'db_table': 'contract_review_departments',
            },
        ),
    ]
